spring:
  application:
    name: middle
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8081

project:
  http:
    enabled: false
  memory:
    enabled: true
  register:
    path: "http://localhost:8082/v2/users"
  create_account:
    path: "http://localhost:8082/v2/users/{id}/accounts"
  get_user_accounts:
    path: "http://localhost:8082/v2/users/{id}/accounts"
  transfer:
    path: "http://localhost:8082/transfer"
