spring:
  application:
    name: middle

project:
  http:
    enabled: false
  memory:
    enabled: true
  register:
    path: "http://localhost:8080/v2/users"
  create_account:
    path: "http://localhost:8080/v2/users/{id}/accounts"
  get_user_accounts:
    path: "http://localhost:8080/v2/users/{id}/accounts"
