spring:
  application:
    name: middle

project:
  http:
    enabled: true
  memory:
    enabled: false
  register:
    path: "http://localhost:8080/v2/users"
  create_account:
    path: "http://localhost:8080/v2/users/new"
