spring:
  application:
    name: middle
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

project:
  http:
    enabled: false
  memory:
    enabled: true
  register:
    path: "http://localhost:8080/v2/users"
  create_account:
    path: "http://localhost:8080/v2/users/{id}/accounts"
  get_user_accounts:
    path: "http://localhost:8080/v2/users/{id}/accounts"
  transfer:
    path: "http://localhost:8080/transfer"
